#!/bin/sh
# prints battery level and charging status
echo $(
if [ "$(upower -i $(upower -e) | grep online | awk '{print $2}' 2>&1)" = "yes" ]; then
	echo ""
else
        echo ""
fi
echo $(cat /sys/class/power_supply/BAT0/capacity)%)
